#!/usr/bin/env php
<?php

$opts = parseOpts();

$prod = diff('packages', $opts['from'], $opts['to']);
$dev = diff('packages-dev', $opts['from'], $opts['to']);

if ($opts['json']) {
    $opts = ($opt['pretty']) ? JSON_PRETTY_PRINT : 0;
    print json_encode(array('changes' => $prod, 'changes-dev' => $dev), $opts);
    return;
}

$useMD = $opts['md'];

print tableize('Production Changes', $prod, $useMD);
print tableize('Dev Changes', $dev, $useMD);

function diff($key, $from, $to) {

    $pkgs = array();

    $data = load($from);

    foreach($data->$key as $pkg) {
        $pkgs[$pkg->name] = array(version($pkg), 'REMOVED');
    }

    $data = load($to);

    foreach($data->$key as $pkg) {
        if (! array_key_exists($pkg->name, $pkgs)) {
            $pkgs[$pkg->name] = array('NEW', version($pkg));
            continue;
        }

        if ($pkgs[$pkg->name][0] == version($pkg)) {
            unset($pkgs[$pkg->name]);
        } else {
            $pkgs[$pkg->name][1] = version($pkg);
        }
    }

    return $pkgs;
}

function version($pkg)
{
    $version = null;
    if(substr($pkg->version,0,4) == 'dev-')
    {
        $version = substr($pkg->source->reference,0,7);
    }
    else
    {
        $version = $pkg->version;
    }
    return $version;
}

function tableize($header, $data, $useMD) {
    if (empty($data)) return '';

    $widths = array(maxLength(array_merge(array($header), array_keys($data))));

    for($i = 0; $i < count(reset($data)); $i++) {
        $widths[] = maxLength(array_map(function($k) use ($data, $i) { return $data[$k][$i]; }, array_keys($data)));
    }

    $total_width = array_sum($widths) + (count($widths) * 3) + 1;

    $lines[] = separatorLine($total_width, count($widths), $useMD, false);
    $lines[] = tabelizeLine(array($header, 'From', 'To'), $widths);
    $lines[] = separatorLine($total_width, count($widths), $useMD, true);

    foreach($data as $key => $v) {
        $lines[] = tabelizeLine(array_merge(array($key), $v), $widths);
    }

    $lines[] = separatorLine($total_width, count($widths), $useMD, false);

    return implode(PHP_EOL, array_filter($lines)) . PHP_EOL . PHP_EOL;
}

function separatorLine($total_width, $nElements, $useMD, $showInMD) {
    if ($useMD && !$showInMD) {
        return '';
    }

    if ($useMD) {
        return implode('|', array_merge([''], array_fill(0, $nElements, '-'), ['']));
    } else {
        return '+' . str_repeat('-', $total_width - 2) . '+';
    }
}

function maxLength(array $array) {
    return max(array_map('strlen', $array));
}

function tabelizeLine($data, $widths) {
    $fields = array();
    $count = max(array(count($data), count($widths)));
    for($i = 0; $i < $count; $i++) {
        $value = ($i >= count($data)) ? '' : $data[$i];
        $width = ($i >= count($widths)) ? strlen($value) : $widths[$i];
        $fields[] = sprintf("%-{$width}s", $value);
    }
    return '| ' . implode(' | ', $fields) . ' |';
}

function load($fileish) {
    $orig = $fileish;

    if (empty($fileish)) {
        $fileish = 'composer.lock';
    }

    if (file_exists($fileish)) {
        return mustDecodeJson(file_get_contents($fileish), $fileish);
    }

    if (strpos($fileish, ':') === false) {
        $fileish .= ':composer.lock';
    }

    $lines = '';

    exec('git show '. escapeshellarg($fileish), $lines, $exit);

    if ($exit !== 0) {
        error_log("Error: cannot open $orig or find it in git as $fileish");
        exit(1);
    }

    return mustDecodeJson(implode("\n", $lines), $fileish);
}

function mustDecodeJson($json, $context) {
    $data = json_decode($json);

    if (empty($data)) {
        error_log("Error: contents from $context does not decode as json");
        exit(1);
    }

    return $data;
}

function parseOpts() {
    $given = getopt('h', array('from:', 'to:', 'json', 'pretty', 'help', 'md'));

    if (array_key_exists('h', $given) || array_key_exists('help', $given)) {
        usage();
    }

    return array(
        'from' => array_key_exists('from', $given) ? $given['from'] : 'HEAD',
        'to' => array_key_exists('to', $given) ? $given['to'] : '',
        'json' => array_key_exists('json', $given),
        'pretty' => version_compare(PHP_VERSION, '5.4.0', '>=') && array_key_exists('pretty', $given),
        'md' => array_key_exists('md', $given),
    );
}

function usage() {
    print <<<EOF
Usage: composer-lock-diff [options]

Options:
  -h --help  Print this message
  --from     The file, git ref, or git ref with filename to compare from (HEAD:composer.lock)
  --to       The file, git ref, or git ref with filename to compare to (composer.lock)
  --json     Format output as JSON
  --pretty   Pretty print JSON output (PHP >= 5.4.0)
  --md       Use markdown instead of plain text

EOF;

    exit(0);
}

